apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: cluster-config
spec:
  targetNamespace: ingress-nginx
  releaseName: nginx-ingress-controller-test
  chart:
    spec:
      chart: ingres-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: cluster-config
      version: "4.2.0"
  interval: 1h0m0s
  #install:
  #  remediation:
  #    retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  #values:
  #  service:
  #    type: NodePort
  #  ingressClassResource:
  #    name: nginx
